# Generated by Django 6.0.1 on 2026-04-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain_resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
