# Generated by Django 6.0.3 on 2026-03-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain_resume', '0002_department_subdepartment_resume_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
