# Generated by Django 6.0.3 on 2026-03-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain_resume', '0003_resume_email_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
