# Generated by Django 6.0.1 on 2026-04-28 07:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maintain_resume", "0002_resume_is_bookmarked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
