# Generated by Django 6.0.1 on 2026-04-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintain_resume", "0003_alter_resume_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
