# Generated by Django 6.0.1 on 2026-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintain_resume", "0004_resume_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.URLField(),
        ),
    ]
